version: '3'
services:
    db:
          build:
              context: .
              dockerfile: docker/mysql/Dockerfile
          environment:
              MYSQL_DATABASE: ${db_name}
              MYSQL_ROOT_PASSWORD: ${db_password}
          command: --default-authentication-plugin=mysql_native_password
          restart: unless-stopped
          volumes:
              - ./db:/usr/data
          ports:
              - 3306:3306
    web:
          build:
              context: .
              dockerfile: docker/apache/Dockerfile
              args:
                  uid: ${UID}
          environment:
              - APACHE_RUN_USER=#${UID}
              - APACHE_RUN_GROUP=#${UID}
          restart: unless-stopped
          volumes:
              - ./:/var/www/html
              - ./docker/apache/apache_log:/var/log/apache2
          ports:
              - 80:80
          depends_on:
              - db
          links:
              - db
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker/rabbitmq/log/:/var/log/rabbitmq
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./docker/redis/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
volumes:
    db:
